import {
  ArticleWithRelations,
  ArticleWithRelationsMinimal,
  CategoryWithChildren,
  LocationWithChildren,
  VideoWithRelations,
  Category,
  Location,
  PhotoGallery,
  GalleryImage,
} from '@/types';

export const fallbackSiteSettings = {
  id: 'singleton',
  siteName: 'Garjane News',
  siteNameKn: 'ಗರ್ಜನೆ ನ್ಯೂಸ್',
  tagline: 'Your Local News, Your Voice',
  taglineKn: 'ನಿಮ್ಮ ಊರಿನ ಸುದ್ದಿ, ನಿಮ್ಮ ಧ್ವನಿ',
  description: 'Garjane News brings the latest breaking news, local updates, and investigative reporting from Nelamangala, Bengaluru Rural, and across Karnataka.',
  descriptionKn: 'ನೆಲಮಂಗಲ, ಬೆಂಗಳೂರು ಗ್ರಾಮಾಂತರ ಹಾಗೂ ಕರ್ನಾಟಕದ ಸಮಗ್ರ, ನಿಖರ ಮತ್ತು ವಸ್ತುನಿಷ್ಠ ಸುದ್ದಿಗಳ ಮುಂಚೂಣಿ ತಾಣ.',
  logoUrl: '/logo.png',
  faviconUrl: '/favicon.ico',
  defaultLanguage: 'kn',
  supportedLanguages: ['kn', 'en'],
  socialLinks: {
    facebook: 'https://facebook.com/garjanenews',
    twitter: 'https://twitter.com/garjanenews',
    instagram: 'https://instagram.com/garjanenews',
    youtube: 'https://youtube.com/@garjanenews',
    email: 'editor@garjanenews.com',
    phone: '+91 98450 12345',
  },
  seoDefaults: {},
  analyticsCode: null,
  adsTxtContent: null,
  maintenanceMode: false,
  updatedAt: new Date(),
};

export const fallbackCategories: CategoryWithChildren[] = [
  {
    id: 'cat-nelamangala',
    name: 'Nelamangala',
    nameKn: 'ನೆಲಮಂಗಲ',
    slug: 'nelamangala',
    description: 'Local updates and events from Nelamangala and surrounding taluks',
    descriptionKn: 'ನೆಲಮಂಗಲ ತಾಲೂಕು ಮತ್ತು ಸುತ್ತಮುತ್ತಲಿನ ಸಮಗ್ರ ಸ್ಥಳೀಯ ಸುದ್ದಿಗಳು',
    color: '#DC2626',
    icon: 'MapPin',
    parentId: null,
    displayOrder: 1,
    isActive: true,
    isFeatured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    children: [],
    _count: { articles: 18 },
  },
  {
    id: 'cat-karnataka',
    name: 'Karnataka',
    nameKn: 'ಕರ್ನಾಟಕ',
    slug: 'karnataka',
    description: 'Statewide news, policy updates, and breaking developments',
    descriptionKn: 'ರಾಜ್ಯ ರಾಜಕಾರಣ, ಆಡಳಿತ ಹಾಗೂ ಕರ್ನಾಟಕದ ಪ್ರಮುಖ ಘಟನೆಗಳು',
    color: '#D97706',
    icon: 'Landmark',
    parentId: null,
    displayOrder: 2,
    isActive: true,
    isFeatured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    children: [],
    _count: { articles: 24 },
  },
  {
    id: 'cat-bengaluru',
    name: 'Bengaluru',
    nameKn: 'ಬೆಂಗಳೂರು',
    slug: 'bengaluru',
    description: 'City news, civic issues, traffic, and infrastructure',
    descriptionKn: 'ಬೆಂಗಳೂರು ನಗರ, ಸಂಚಾರ ದಟ್ಟಣೆ ಹಾಗೂ ನಾಗರಿಕ ಸಮಸ್ಯೆಗಳ ವರದಿ',
    color: '#2563EB',
    icon: 'Building2',
    parentId: null,
    displayOrder: 3,
    isActive: true,
    isFeatured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    children: [],
    _count: { articles: 15 },
  },
  {
    id: 'cat-politics',
    name: 'Politics',
    nameKn: 'ರಾಜಕೀಯ',
    slug: 'politics',
    description: 'Political debates, election news, and assembly coverage',
    descriptionKn: 'ವಿಧಾನಸಭೆ, ಪಕ್ಷ ರಾಜಕೀಯ ಮತ್ತು ಪ್ರಮುಖ ನಾಯಕರ ಹೇಳಿಕೆಗಳು',
    color: '#7C3AED',
    icon: 'Vote',
    parentId: null,
    displayOrder: 4,
    isActive: true,
    isFeatured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    children: [],
    _count: { articles: 20 },
  },
  {
    id: 'cat-crime',
    name: 'Crime',
    nameKn: 'ಅಪರಾಧ',
    slug: 'crime',
    description: 'Law and order, police investigations, and court trials',
    descriptionKn: 'ಪೊಲೀಸ್ ತನಿಖೆ, ನ್ಯಾಯಾಲಯ ಹಾಗೂ ಕಾನೂನು ಸುವ್ಯವಸ್ಥೆ ವರದಿಗಳು',
    color: '#991B1B',
    icon: 'ShieldAlert',
    parentId: null,
    displayOrder: 5,
    isActive: true,
    isFeatured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
    children: [],
    _count: { articles: 12 },
  },
  {
    id: 'cat-sports',
    name: 'Sports',
    nameKn: 'ಕ್ರೀಡೆ',
    slug: 'sports',
    description: 'Cricket, local sports tournaments, and athletic achievements',
    descriptionKn: 'ಕ್ರಿಕೆಟ್, ಕಬ್ಬಡಿ ಹಾಗೂ ಸ್ಥಳೀಯ ಕ್ರೀಡಾಪಟುಗಳ ಸಾಧನೆ',
    color: '#059669',
    icon: 'Trophy',
    parentId: null,
    displayOrder: 6,
    isActive: true,
    isFeatured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
    children: [],
    _count: { articles: 9 },
  },
  {
    id: 'cat-entertainment',
    name: 'Cinema',
    nameKn: 'ಸಿನೆಮಾ',
    slug: 'entertainment',
    description: 'Sandalwood news, movie reviews, and celebrity interviews',
    descriptionKn: 'ಸ್ಯಾಂಡಲ್‌ವುಡ್ ಸುದ್ದಿ, ಸಿನಿಮಾ ವಿಮರ್ಶೆ ಹಾಗೂ ತಾರೆಯರ ಮಾತು',
    color: '#DB2777',
    icon: 'Film',
    parentId: null,
    displayOrder: 7,
    isActive: true,
    isFeatured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
    children: [],
    _count: { articles: 14 },
  },
  {
    id: 'cat-business',
    name: 'Business',
    nameKn: 'ವ್ಯಾಪಾರ',
    slug: 'business',
    description: 'Economy, APMC market rates, and rural business updates',
    descriptionKn: 'ಕೃಷಿ ಮಾರುಕಟ್ಟೆ ದರ, ಉದ್ಯಮ ಹಾಗೂ ಆರ್ಥಿಕ ವ್ಯವಹಾರಗಳ ಮಾಹಿತಿ',
    color: '#0D9488',
    icon: 'TrendingUp',
    parentId: null,
    displayOrder: 8,
    isActive: true,
    isFeatured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
    children: [],
    _count: { articles: 8 },
  },
];

export const fallbackLocations: LocationWithChildren[] = [
  {
    id: 'loc-nelamangala',
    name: 'Nelamangala',
    nameKn: 'ನೆಲಮಂಗಲ',
    slug: 'nelamangala',
    type: 'taluk',
    parentId: null,
    latitude: 13.0968,
    longitude: 77.3917,
    isActive: true,
    displayOrder: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
    children: [],
    _count: { articles: 25 },
  },
  {
    id: 'loc-bengaluru-rural',
    name: 'Bengaluru Rural',
    nameKn: 'ಬೆಂಗಳೂರು ಗ್ರಾಮಾಂತರ',
    slug: 'bengaluru-rural',
    type: 'district',
    parentId: null,
    latitude: 13.2341,
    longitude: 77.5457,
    isActive: true,
    displayOrder: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
    children: [],
    _count: { articles: 30 },
  },
  {
    id: 'loc-bengaluru-urban',
    name: 'Bengaluru Urban',
    nameKn: 'ಬೆಂಗಳೂರು ನಗರ',
    slug: 'bengaluru-urban',
    type: 'district',
    parentId: null,
    latitude: 12.9716,
    longitude: 77.5946,
    isActive: true,
    displayOrder: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
    children: [],
    _count: { articles: 20 },
  },
  {
    id: 'loc-tumakuru',
    name: 'Tumakuru',
    nameKn: 'ತುಮಕೂರು',
    slug: 'tumakuru',
    type: 'district',
    parentId: null,
    latitude: 13.3379,
    longitude: 77.1173,
    isActive: true,
    displayOrder: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
    children: [],
    _count: { articles: 12 },
  },
];

export const fallbackMenuItems = [
  { id: 'm1', label: 'Home', labelKn: 'ಮುಖಪುಟ', slug: 'home', href: '/', parentId: null, displayOrder: 1, isActive: true, isExternal: false, children: [] },
  { id: 'm2', label: 'Nelamangala', labelKn: 'ನೆಲಮಂಗಲ', slug: 'nelamangala', href: '/category/nelamangala', parentId: null, displayOrder: 2, isActive: true, isExternal: false, children: [] },
  { id: 'm3', label: 'Karnataka', labelKn: 'ಕರ್ನಾಟಕ', slug: 'karnataka', href: '/category/karnataka', parentId: null, displayOrder: 3, isActive: true, isExternal: false, children: [] },
  { id: 'm4', label: 'Politics', labelKn: 'ರಾಜಕೀಯ', slug: 'politics', href: '/category/politics', parentId: null, displayOrder: 4, isActive: true, isExternal: false, children: [] },
  { id: 'm5', label: 'Crime', labelKn: 'ಅಪರಾಧ', slug: 'crime', href: '/category/crime', parentId: null, displayOrder: 5, isActive: true, isExternal: false, children: [] },
  { id: 'm6', label: 'Videos', labelKn: 'ವೀಡಿಯೋಗಳು', slug: 'videos', href: '/video', parentId: null, displayOrder: 6, isActive: true, isExternal: false, children: [] },
  { id: 'm7', label: 'Cinema', labelKn: 'ಸಿನೆಮಾ', slug: 'entertainment', href: '/category/entertainment', parentId: null, displayOrder: 7, isActive: true, isExternal: false, children: [] },
];

export const fallbackArticles: ArticleWithRelations[] = [
  {
    id: 'art-1',
    slug: 'nelamangala-highway-flyover-expansion-approved',
    headline: 'Nelamangala-Tumakuru Expressway Expansion: 6-Lane Elevated Corridor Approved by NHAI',
    headlineKn: 'ನೆಲಮಂಗಲ-ತುಮಕೂರು ಎಕ್ಸ್‌ಪ್ರೆಸ್‌ವೇ ವಿಸ್ತರಣೆ: 6 ಪಥದ ಮೇಲ್ಸೇತುವೆ ಕಾರಿಡಾರ್‌ಗೆ ಕೇಂದ್ರ ಸರ್ಕಾರ ಅನುಮೋದನೆ',
    summary: 'NHAI approves comprehensive plan to ease perpetual traffic choke points at Nelamangala toll gate with new elevated structure and dedicated service lanes.',
    summaryKn: 'ನೆಲಮಂಗಲ ಟೋಲ್ ಬಳಿ ನಿತ್ಯದ ಸಂಚಾರ ದಟ್ಟಣೆಗೆ ಮುಕ್ತಿ ನೀಡಲು ರಾಷ್ಟ್ರೀಯ ಹೆದ್ದಾರಿ ಪ್ರಾಧಿಕಾರದಿಂದ ನೂತನ 6 ಪಥದ ಎಲಿವೇಟೆಡ್ ಕಾರಿಡಾರ್ ನಿರ್ಮಾಣಕ್ಕೆ ಹಸಿರು ನಿಶಾನೆ.',
    content: `<p>ನೆಲಮಂಗಲ: ಬೆಂಗಳೂರು-ತುಮಕೂರು ರಾಷ್ಟ್ರೀಯ ಹೆದ್ದಾರಿ-48 ರ ನೆಲಮಂಗಲ ಜಂಕ್ಷನ್‌ನಲ್ಲಿ ನಿತ್ಯವೂ ಸೃಷ್ಟಿಯಾಗುವ ಸಂಚಾರ ದಟ್ಟಣೆಯನ್ನು ನಿವಾರಿಸಲು ಕೇಂದ್ರ ಹೆದ್ದಾರಿ ಪ್ರಾಧಿಕಾರ (NHAI) ಮಹತ್ವದ ಯೋಜನೆಯನ್ನು ಕೈಗೆತ್ತಿಕೊಂಡಿದೆ.</p>
<p>ಸುಮಾರು 1,250 ಕೋಟಿ ರೂಪಾಯಿ ವೆಚ್ಚದಲ್ಲಿ ನೆಲಮಂಗಲ ಬೈಪಾಸ್‌ನಿಂದ ಡಾಬಸ್‌ಪೇಟೆ ತನಕ 6 ಪಥದ ಮೇಲ್ಸೇತುವೆ ಮತ್ತು ಎರಡೂ ಬದಿಗಳಲ್ಲಿ ಪ್ರತ್ಯೇಕ ಸರ್ವಿಸ್ ರಸ್ತೆಗಳನ್ನು ಅಭಿವೃದ್ಧಿಪಡಿಸಲು ಸಮಗ್ರ ಯೋಜನಾ ವರದಿ (DPR) ಸಿದ್ಧಗೊಂಡಿದೆ.</p>
<p>ಸ್ಥಳೀಯ ಶಾಸಕರು ಮತ್ತು ಸಂಸದರ ನೇತೃತ್ವದಲ್ಲಿ ನಡೆದ ಪರಿಶೀಲನಾ ಸಭೆಯಲ್ಲಿ ಈ ಯೋಜನೆಗೆ ಶೀಘ್ರವೇ ಟೆಂಡರ್ ಪ್ರಕ್ರಿಯೆ ಆರಂಭಿಸಲಾಗುವುದು ಎಂದು ಅಧಿಕಾರಿಗಳು ಸ್ಪಷ್ಟಪಡಿಸಿದ್ದಾರೆ. ಇದರಿಂದಾಗಿ ದಿನಂಪ್ರತಿ ಸಂಚರಿಸುವ ಲಕ್ಷಾಂತರ ವಾಹನ ಸವಾರರಿಗೆ ಮತ್ತು ಸ್ಥಳೀಯ ಸಾರ್ವಜನಿಕರಿಗೆ ಸುಗಮ ಸಂಚಾರ ಸಾಧ್ಯವಾಗಲಿದೆ.</p>`,
    contentKn: `<p>ನೆಲಮಂಗಲ: ಬೆಂಗಳೂರು-ತುಮಕೂರು ರಾಷ್ಟ್ರೀಯ ಹೆದ್ದಾರಿ-48 ರ ನೆಲಮಂಗಲ ಜಂಕ್ಷನ್‌ನಲ್ಲಿ ನಿತ್ಯವೂ ಸೃಷ್ಟಿಯಾಗುವ ಸಂಚಾರ ದಟ್ಟಣೆಯನ್ನು ನಿವಾರಿಸಲು ಕೇಂದ್ರ ಹೆದ್ದಾರಿ ಪ್ರಾಧಿಕಾರ (NHAI) ಮಹತ್ವದ ಯೋಜನೆಯನ್ನು ಕೈಗೆತ್ತಿಕೊಂಡಿದೆ.</p>
<p>ಸುಮಾರು 1,250 ಕೋಟಿ ರೂಪಾಯಿ ವೆಚ್ಚದಲ್ಲಿ ನೆಲಮಂಗಲ ಬೈಪಾಸ್‌ನಿಂದ ಡಾಬಸ್‌ಪೇಟೆ ತನಕ 6 ಪಥದ ಮೇಲ್ಸೇತುವೆ ಮತ್ತು ಎರಡೂ ಬದಿಗಳಲ್ಲಿ ಪ್ರತ್ಯೇಕ ಸರ್ವಿಸ್ ರಸ್ತೆಗಳನ್ನು ಅಭಿವೃದ್ಧಿಪಡಿಸಲು ಸಮಗ್ರ ಯೋಜನಾ ವರದಿ (DPR) ಸಿದ್ಧಗೊಂಡಿದೆ.</p>
<p>ಸ್ಥಳೀಯ ಶಾಸಕರು ಮತ್ತು ಸಂಸದರ ನೇತೃತ್ವದಲ್ಲಿ ನಡೆದ ಪರಿಶೀಲನಾ ಸಭೆಯಲ್ಲಿ ಈ ಯೋಜನೆಗೆ ಶೀಘ್ರವೇ ಟೆಂಡರ್ ಪ್ರಕ್ರಿಯೆ ಆರಂಭಿಸಲಾಗುವುದು ಎಂದು ಅಧಿಕಾರಿಗಳು ಸ್ಪಷ್ಟಪಡಿಸಿದ್ದಾರೆ. ಇದರಿಂದಾಗಿ ದಿನಂಪ್ರತಿ ಸಂಚರಿಸುವ ಲಕ್ಷಾಂತರ ವಾಹನ ಸವಾರರಿಗೆ ಮತ್ತು ಸ್ಥಳೀಯ ಸಾರ್ವಜನಿಕರಿಗೆ ಸುಗಮ ಸಂಚಾರ ಸಾಧ್ಯವಾಗಲಿದೆ.</p>`,
    excerpt: 'NHAI approves comprehensive plan to ease traffic choke points at Nelamangala toll gate.',
    excerptKn: 'ನೆಲಮಂಗಲ ಟೋಲ್ ಬಳಿ ನಿತ್ಯದ ಸಂಚಾರ ದಟ್ಟಣೆಗೆ ಮುಕ್ತಿ ನೀಡಲು ನೂತನ 6 ಪಥದ ಎಲಿವೇಟೆಡ್ ಕಾರಿಡಾರ್.',
    featuredImage: 'https://images.unsplash.com/photo-1545459720-aac8509eb02c?w=1200&auto=format&fit=crop&q=80',
    featuredImageAlt: 'Nelamangala Highway Development',
    featuredImageCaption: 'ನೆಲಮಂಗಲ-ತುಮಕೂರು ಎಕ್ಸ್‌ಪ್ರೆಸ್‌ವೇ ಕಾಮಗಾರಿ ಪರಿಶೀಲನೆ',
    status: 'PUBLISHED',
    breakingLevel: 'BREAKING',
    isFeatured: true,
    isEditorPick: true,
    isLive: false,
    allowComments: true,
    viewCount: 14250,
    readTime: 4,
    publishedAt: new Date(Date.now() - 1000 * 60 * 30),
    scheduledAt: null,
    authorId: 'usr-editor',
    reporterId: 'rep-nelamangala',
    categoryId: 'cat-nelamangala',
    locationId: 'loc-nelamangala',
    seoTitle: 'ನೆಲಮಂಗಲ ಹೆದ್ದಾರಿ ವಿಸ್ತರಣೆ: 6 ಪಥದ ಮೇಲ್ಸೇತುವೆ ಮಂಜೂರು',
    seoDescription: 'ನೆಲಮಂಗಲ ಟೋಲ್ ಟ್ರಾಫಿಕ್ ಸಮಸ್ಯೆಗೆ ಶಾಶ್ವತ ಪರಿಹಾರ: ನೂತನ ಎಲಿವೇಟೆಡ್ ರಸ್ತೆ ಯೋಜನೆಗೆ ಒಪ್ಪಿಗೆ.',
    seoKeywords: ['Nelamangala', 'Highway', 'Karnataka', 'Traffic', 'ನೆಲಮಂಗಲ'],
    canonicalUrl: null,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2),
    updatedAt: new Date(),
    category: fallbackCategories[0],
    author: { id: 'usr-editor', email: 'editor@garjanenews.com', passwordHash: '', name: 'ಸಂಪಾದಕೀಯ ಮಂಡಳಿ', avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120', role: 'EDITOR', bio: 'ಗರ್ಜನೆ ನ್ಯೂಸ್ ಮುಖ್ಯ ಸಂಪಾದಕರು', bioKn: null, location: 'ನೆಲಮಂಗಲ', phone: null, isActive: true, lastLoginAt: null, createdAt: new Date(), updatedAt: new Date() },
    reporter: { id: 'rep-nelamangala', userId: 'usr-editor', user: { id: 'usr-editor', email: 'editor@garjanenews.com', passwordHash: '', name: 'ರಮೇಶ್ ಗೌಡ (ನೆಲಮಂಗಲ ವರದಿಗಾರ)', avatar: null, role: 'REPORTER', bio: null, bioKn: null, location: null, phone: null, isActive: true, lastLoginAt: null, createdAt: new Date(), updatedAt: new Date() }, beat: 'ಸ್ಥಳೀಯ ರಾಜಕೀಯ & ಅಭಿವೃದ್ಧಿ', specialization: ['ನೆಲಮಂಗಲ', 'ರೈತರ ಸಮಸ್ಯೆಗಳು'], socialLinks: null, isVerified: true, joinedAt: new Date(), createdAt: new Date(), updatedAt: new Date() },
    location: fallbackLocations[0],
    tags: [
      { id: 'at-1', articleId: 'art-1', tagId: 'tag-nelamangala', tag: { id: 'tag-nelamangala', name: 'Nelamangala', nameKn: 'ನೆಲಮಂಗಲ', slug: 'nelamangala', color: '#DC2626', createdAt: new Date() } },
      { id: 'at-2', articleId: 'art-1', tagId: 'tag-infrastructure', tag: { id: 'tag-infrastructure', name: 'Infrastructure', nameKn: 'ರಸ್ತೆ ಅಭಿವೃದ್ಧಿ', slug: 'infrastructure', color: '#2563EB', createdAt: new Date() } },
    ],
    media: [
      { id: 'med-1', articleId: 'art-1', type: 'IMAGE', url: 'https://images.unsplash.com/photo-1545459720-aac8509eb02c?w=1200&auto=format&fit=crop&q=80', alt: 'Highway', caption: 'ನೆಲಮಂಗಲ ಹೆದ್ದಾರಿ', captionKn: 'ನೆಲಮಂಗಲ ಹೆದ್ದಾರಿ', thumbnailUrl: null, width: 1200, height: 800, duration: null, displayOrder: 0, createdAt: new Date() },
    ],
    galleries: [],
    liveUpdates: [],
    views: [],
    relatedArticles: [],
    relatedTo: [],
    breakingNews: [],
    comments: [],
  },
  {
    id: 'art-2',
    slug: 'karnataka-cabinet-key-decisions-farmers-loan-relief',
    headline: 'Karnataka Cabinet Greenlights ₹2,000 Crore Drought and Irrigation Relief Package',
    headlineKn: 'ಕರ್ನಾಟಕ ಸಚಿವ ಸಂಪುಟ ಮಹತ್ವದ ತೀರ್ಮಾನ: ರೈತರ ನೀರಾವರಿ ಮತ್ತು ಬರ ಪರಿಹಾರಕ್ಕೆ ₹2,000 ಕೋಟಿ ಅನುದಾನ',
    summary: 'Chief Minister announces direct crop loss assistance and accelerated work on pending lift irrigation schemes across southern Karnataka.',
    summaryKn: 'ದಕ್ಷಿಣ ಕರ್ನಾಟಕ ಸೇರಿದಂತೆ ರಾಜ್ಯದ ಬರಪೀಡಿತ ತಾಲೂಕುಗಳ ರೈತರಿಗೆ ನೇರ ನಷ್ಟ ಪರಿಹಾರ ಹಾಗೂ ಬಾಕಿ ನೀರಾವರಿ ಕಾಮಗಾರಿ ಪೂರ್ಣಗೊಳಿಸಲು ಸಚಿವ ಸಂಪುಟ ಒಪ್ಪಿಗೆ.',
    content: '<p>ಬೆಂಗಳೂರು: ರಾಜ್ಯದ ರೈತರ ಹಿತದೃಷ್ಟಿಯಿಂದ ಸಚಿವ ಸಂಪುಟ ಸಭೆಯಲ್ಲಿ ಮಹತ್ವದ ತೀರ್ಮಾನಗಳನ್ನು ಕೈಗೊಳ್ಳಲಾಗಿದ್ದು, ಬರ ಪರಿಹಾರ ಮತ್ತು ನೀರಾವರಿ ಯೋಜನೆಗಳ ತ್ವರಿತ ಅನುಷ್ಠಾನಕ್ಕೆ 2,000 ಕೋಟಿ ರೂ. ಪ್ಯಾಕೇಜ್ ಘೋಷಿಸಲಾಗಿದೆ.</p>',
    contentKn: '<p>ಬೆಂಗಳೂರು: ರಾಜ್ಯದ ರೈತರ ಹಿತದೃಷ್ಟಿಯಿಂದ ಸಚಿವ ಸಂಪುಟ ಸಭೆಯಲ್ಲಿ ಮಹತ್ವದ ತೀರ್ಮಾನಗಳನ್ನು ಕೈಗೊಳ್ಳಲಾಗಿದ್ದು, ಬರ ಪರಿಹಾರ ಮತ್ತು ನೀರಾವರಿ ಯೋಜನೆಗಳ ತ್ವರಿತ ಅನುಷ್ಠಾನಕ್ಕೆ 2,000 ಕೋಟಿ ರೂ. ಪ್ಯಾಕೇಜ್ ಘೋಷಿಸಲಾಗಿದೆ.</p>',
    excerpt: 'State cabinet sanctions comprehensive financial relief for drought affected districts.',
    excerptKn: 'ಬರ ಪರಿಹಾರ ಮತ್ತು ನೀರಾವರಿ ಯೋಜನೆಗಳಿಗೆ 2,000 ಕೋಟಿ ರೂ. ಅನುದಾನ.',
    featuredImage: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=1200&auto=format&fit=crop&q=80',
    featuredImageAlt: 'Karnataka Agriculture',
    featuredImageCaption: 'ಕರ್ನಾಟಕ ಕೃಷಿ ಮತ್ತು ನೀರಾವರಿ ಯೋಜನೆಗಳು',
    status: 'PUBLISHED',
    breakingLevel: 'URGENT',
    isFeatured: false,
    isEditorPick: true,
    isLive: false,
    allowComments: true,
    viewCount: 9800,
    readTime: 3,
    publishedAt: new Date(Date.now() - 1000 * 60 * 90),
    scheduledAt: null,
    authorId: 'usr-editor',
    reporterId: null,
    categoryId: 'cat-karnataka',
    locationId: 'loc-bengaluru-rural',
    seoTitle: 'ಕರ್ನಾಟಕ ಸಚಿವ ಸಂಪುಟ: ರೈತರಿಗೆ ₹2000 ಕೋಟಿ ಪರಿಹಾರ',
    seoDescription: 'ರಾಜ್ಯ ಸರ್ಕಾರದ ಮಹತ್ವದ ತೀರ್ಮಾನ: ಬರ ಪರಿಹಾರ ಮತ್ತು ನೀರಾವರಿ ಯೋಜನೆಗಳಿಗೆ ಅನುದಾನ ಬಿಡುಗಡೆ.',
    seoKeywords: ['Karnataka', 'Cabinet', 'Farmers', 'Agriculture'],
    canonicalUrl: null,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 4),
    updatedAt: new Date(),
    category: fallbackCategories[1],
    author: { id: 'usr-editor', email: 'editor@garjanenews.com', passwordHash: '', name: 'ವಿಶೇಷ ವರದಿಗಾರ', avatar: null, role: 'EDITOR', bio: null, bioKn: null, location: 'ಬೆಂಗಳೂರು', phone: null, isActive: true, lastLoginAt: null, createdAt: new Date(), updatedAt: new Date() },
    reporter: null,
    location: fallbackLocations[1],
    tags: [],
    media: [],
    galleries: [],
    liveUpdates: [],
    views: [],
    relatedArticles: [],
    relatedTo: [],
    breakingNews: [],
    comments: [],
  },
  {
    id: 'art-3',
    slug: 'bengaluru-rural-apmc-onion-tomato-market-price-surge',
    headline: 'APMC Market Watch: Onion and Tomato Arrivals Double, Wholesale Rates Stabilize',
    headlineKn: 'ನೆಲಮಂಗಲ ಮತ್ತು ಯಶವಂತಪುರ ಎಪಿಎಂಸಿ: ಈರುಳ್ಳಿ, ಟೊಮೆಟೊ ಆವಕ ಹೆಚ್ಚಳ, ಬೆಲೆ ಸ್ಥಿರತೆ',
    summary: 'Bumper crop arrivals from Kolar, Chikkaballapur, and Nelamangala bring respite to consumers while wholesale prices hold steady.',
    summaryKn: 'ನೆಲಮಂಗಲ ಸುತ್ತಮುತ್ತಲಿನ ಕೃಷಿ ಪ್ರದೇಶಗಳಿಂದ ತರಕಾರಿ ಆವಕ ಹೆಚ್ಚಾಗಿದ್ದು, ಗ್ರಾಹಕರಿಗೆ ತುಸು ನಿರಾಳತೆ ದೊರೆತಿದೆ.',
    content: '<p>ನೆಲಮಂಗಲ: ಕಳೆದ ವಾರ ಗಗನಕ್ಕೇರಿದ್ದ ತರಕಾರಿ ಬೆಲೆಗಳು ಇದೀಗ ಮಾರುಕಟ್ಟೆಗೆ ಭಾರಿ ಪ್ರಮಾಣದ ಆವಕ ಆರಂಭವಾಗುತ್ತಿದ್ದಂತೆ ಇಳಿಮುಖವಾಗತೊಡಗಿವೆ.</p>',
    contentKn: '<p>ನೆಲಮಂಗಲ: ಕಳೆದ ವಾರ ಗಗನಕ್ಕೇರಿದ್ದ ತರಕಾರಿ ಬೆಲೆಗಳು ಇದೀಗ ಮಾರುಕಟ್ಟೆಗೆ ಭಾರಿ ಪ್ರಮಾಣದ ಆವಕ ಆರಂಭವಾಗುತ್ತಿದ್ದಂತೆ ಇಳಿಮುಖವಾಗತೊಡಗಿವೆ.</p>',
    excerpt: 'Vegetable prices ease at Nelamangala and Yeshwanthpur APMC markets.',
    excerptKn: 'ಮಾರುಕಟ್ಟೆಗೆ ಭಾರಿ ಪ್ರಮಾಣದ ಆವಕ ಆರಂಭವಾಗುತ್ತಿದ್ದಂತೆ ತರಕಾರಿ ದರ ಇಳಿಕೆ.',
    featuredImage: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=1200&auto=format&fit=crop&q=80',
    featuredImageAlt: 'Vegetable Market',
    featuredImageCaption: 'ಎಪಿಎಂಸಿ ಮಾರುಕಟ್ಟೆ ವರದಿ',
    status: 'PUBLISHED',
    breakingLevel: 'NORMAL',
    isFeatured: false,
    isEditorPick: true,
    isLive: false,
    allowComments: true,
    viewCount: 6540,
    readTime: 3,
    publishedAt: new Date(Date.now() - 1000 * 60 * 180),
    scheduledAt: null,
    authorId: 'usr-editor',
    reporterId: null,
    categoryId: 'cat-business',
    locationId: 'loc-nelamangala',
    seoTitle: 'ಎಪಿಎಂಸಿ ಮಾರುಕಟ್ಟೆ ದರ ವಿವರ',
    seoDescription: 'ನೆಲಮಂಗಲ ಎಪಿಎಂಸಿ ಮಾರುಕಟ್ಟೆಯಲ್ಲಿ ತರಕಾರಿ ಬೆಲೆ ವಿವರ.',
    seoKeywords: ['APMC', 'Market', 'Nelamangala', 'Vegetables'],
    canonicalUrl: null,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 6),
    updatedAt: new Date(),
    category: fallbackCategories[7],
    author: { id: 'usr-editor', email: 'editor@garjanenews.com', passwordHash: '', name: 'ಗರ್ಜನೆ ಮಾರುಕಟ್ಟೆ ಡೆಸ್ಕ್', avatar: null, role: 'EDITOR', bio: null, bioKn: null, location: null, phone: null, isActive: true, lastLoginAt: null, createdAt: new Date(), updatedAt: new Date() },
    reporter: null,
    location: fallbackLocations[0],
    tags: [],
    media: [],
    galleries: [],
    liveUpdates: [],
    views: [],
    relatedArticles: [],
    relatedTo: [],
    breakingNews: [],
    comments: [],
  },
  {
    id: 'art-4',
    slug: 'kannada-cinema-industry-new-releases-box-office',
    headline: 'Sandalwood This Week: Big Ticket Action Drama Set for Grand Theatrical Release',
    headlineKn: 'ಸ್ಯಾಂಡಲ್‌ವುಡ್ ಸುದ್ದಿ: ಈ ವಾರ ರಾಜ್ಯಾದ್ಯಂತ ಬಹುನಿರೀಕ್ಷಿತ ಆಕ್ಷನ್ ಸಿನೆಮಾ ಭರ್ಜರಿ ಬಿಡುಗಡೆ',
    summary: 'Single screens and multiplexes in Bengaluru and Nelamangala report massive advance bookings for this weekend’s festive release.',
    summaryKn: 'ಬೆಂಗಳೂರು ಹಾಗೂ ನೆಲಮಂಗಲದ ಚಿತ್ರಮಂದಿರಗಳಲ್ಲಿ ಮುಂಗಡ ಟಿಕೆಟ್ ಬುಕ್ಕಿಂಗ್‌ಗೆ ಪ್ರೇಕ್ಷಕರಿಂದ ಅಭೂತಪೂರ್ವ ಸ್ಪಂದನೆ ವ್ಯಕ್ತವಾಗಿದೆ.',
    content: '<p>ಬೆಂಗಳೂರು: ಕನ್ನಡ ಚಿತ್ರರಂಗದ ಬಹುನಿರೀಕ್ಷಿತ ಆಕ್ಷನ್ ಎಂಟರ್ಟೈನರ್ ಈ ವಾರಾಂತ್ಯಕ್ಕೆ ತೆರೆಕಾಣಲು ಸಜ್ಜಾಗಿದ್ದು, ಟ್ರೇಲರ್ ಸಾಮಾಜಿಕ ಜಾಲತಾಣಗಳಲ್ಲಿ ಸಂಚಲನ ಸೃಷ್ಟಿಸಿದೆ.</p>',
    contentKn: '<p>ಬೆಂಗಳೂರು: ಕನ್ನಡ ಚಿತ್ರರಂಗದ ಬಹುನಿರೀಕ್ಷಿತ ಆಕ್ಷನ್ ಎಂಟರ್ಟೈನರ್ ಈ ವಾರಾಂತ್ಯಕ್ಕೆ ತೆರೆಕಾಣಲು ಸಜ್ಜಾಗಿದ್ದು, ಟ್ರೇಲರ್ ಸಾಮಾಜಿಕ ಜಾಲತಾಣಗಳಲ್ಲಿ ಸಂಚಲನ ಸೃಷ್ಟಿಸಿದೆ.</p>',
    excerpt: 'Advance bookings surge for weekend Kannada film release.',
    excerptKn: 'ಕನ್ನಡ ಚಿತ್ರರಂಗದ ಬಹುನಿರೀಕ್ಷಿತ ಸಿನೆಮಾ ಈ ವಾರಾಂತ್ಯಕ್ಕೆ ಬಿಡುಗಡೆ.',
    featuredImage: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=1200&auto=format&fit=crop&q=80',
    featuredImageAlt: 'Cinema theatre',
    featuredImageCaption: 'ಕನ್ನಡ ಚಲನಚಿತ್ರ ರಂಗದ ತಾಜಾ ಅಪ್‌ಡೇಟ್',
    status: 'PUBLISHED',
    breakingLevel: 'NORMAL',
    isFeatured: false,
    isEditorPick: true,
    isLive: false,
    allowComments: true,
    viewCount: 11200,
    readTime: 2,
    publishedAt: new Date(Date.now() - 1000 * 60 * 240),
    scheduledAt: null,
    authorId: 'usr-editor',
    reporterId: null,
    categoryId: 'cat-entertainment',
    locationId: 'loc-bengaluru-urban',
    seoTitle: 'ಸ್ಯಾಂಡಲ್‌ವುಡ್ ವಾರಾಂತ್ಯದ ಬಿಡುಗಡೆ',
    seoDescription: 'ಕನ್ನಡ ಚಿತ್ರರಂಗದ ಹೊಸ ಚಿತ್ರಗಳ ಬಿಡುಗಡೆ ವಿವರ.',
    seoKeywords: ['Cinema', 'Sandalwood', 'Movies', 'Kannada'],
    canonicalUrl: null,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 8),
    updatedAt: new Date(),
    category: fallbackCategories[6],
    author: { id: 'usr-editor', email: 'editor@garjanenews.com', passwordHash: '', name: 'ಸಿನೆಮಾ ಡೆಸ್ಕ್', avatar: null, role: 'EDITOR', bio: null, bioKn: null, location: null, phone: null, isActive: true, lastLoginAt: null, createdAt: new Date(), updatedAt: new Date() },
    reporter: null,
    location: fallbackLocations[2],
    tags: [],
    media: [],
    galleries: [],
    liveUpdates: [],
    views: [],
    relatedArticles: [],
    relatedTo: [],
    breakingNews: [],
    comments: [],
  },
  {
    id: 'art-5',
    slug: 'nelamangala-rural-drinking-water-lake-rejuvenation-project',
    headline: 'Mission Lake Revival: 12 Water Bodies in Nelamangala Taluk Undergo Desilting',
    headlineKn: 'ಕೆರೆ ಸಂರಕ್ಷಣಾ ಅಭಿಯಾನ: ನೆಲಮಂಗಲ ತಾಲೂಕಿನ 12 ಪ್ರಮುಖ ಕೆರೆಗಳ ಹೂಳೆತ್ತುವ ಕಾಮಗಾರಿಗೆ ಚಾಲನೆ',
    summary: 'Local community groups and district administration join hands to recharge groundwater levels before the pre-monsoon rains.',
    summaryKn: 'ಮುಂಗಾರು ಪೂರ್ವ ಮಳೆಗೂ ಮುನ್ನ ಅಂತರ್ಜಲ ಮಟ್ಟ ಹೆಚ್ಚಿಸಲು ಗ್ರಾಮ ಪಂಚಾಯಿತಿ ಮತ್ತು ಪರಿಸರ ಸಂಘಟನೆಗಳ ಸಹಯೋಗದಲ್ಲಿ ಬೃಹತ್ ಕೆರೆ ಪುನಶ್ಚೇತನ.',
    content: '<p>ನೆಲಮಂಗಲ: ತಾಲೂಕಿನ ಗ್ರಾಮೀಣ ಪ್ರದೇಶಗಳಲ್ಲಿ ನೀರಿನ ಅಭಾವ ತಪ್ಪಿಸಲು ಹಾಗೂ ಕೆರೆಗಳ ಜೀವಕಳೆ ಮರಳಿ ತರಲು ಜಿಲ್ಲಾಡಳಿತದ ವತಿಯಿಂದ 12 ಕೆರೆಗಳ ಹೂಳೆತ್ತುವ ಕಾರ್ಯಕ್ಕೆ ಹಸಿರು ನಿಶಾನೆ ತೋರಿಸಲಾಗಿದೆ.</p>',
    contentKn: '<p>ನೆಲಮಂಗಲ: ತಾಲೂಕಿನ ಗ್ರಾಮೀಣ ಪ್ರದೇಶಗಳಲ್ಲಿ ನೀರಿನ ಅಭಾವ ತಪ್ಪಿಸಲು ಹಾಗೂ ಕೆರೆಗಳ ಜೀವಕಳೆ ಮರಳಿ ತರಲು ಜಿಲ್ಲಾಡಳಿತದ ವತಿಯಿಂದ 12 ಕೆರೆಗಳ ಹೂಳೆತ್ತುವ ಕಾರ್ಯಕ್ಕೆ ಹಸಿರು ನಿಶಾನೆ ತೋರಿಸಲಾಗಿದೆ.</p>',
    excerpt: 'Community-led lake revival project launched across Nelamangala taluk.',
    excerptKn: 'ಅಂತರ್ಜಲ ಮಟ್ಟ ಸುಧಾರಣೆಗೆ ನೆಲಮಂಗಲದಲ್ಲಿ 12 ಕೆರೆಗಳ ಪುನಶ್ಚೇತನ ಕಾರ್ಯಾರಂಭ.',
    featuredImage: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&auto=format&fit=crop&q=80',
    featuredImageAlt: 'Lake rejuvenation',
    featuredImageCaption: 'ನೆಲಮಂಗಲ ಗ್ರಾಮಾಂತರ ಕೆರೆ ಪುನಶ್ಚೇತನ',
    status: 'PUBLISHED',
    breakingLevel: 'NORMAL',
    isFeatured: false,
    isEditorPick: false,
    isLive: false,
    allowComments: true,
    viewCount: 4300,
    readTime: 3,
    publishedAt: new Date(Date.now() - 1000 * 60 * 360),
    scheduledAt: null,
    authorId: 'usr-editor',
    reporterId: null,
    categoryId: 'cat-nelamangala',
    locationId: 'loc-nelamangala',
    seoTitle: 'ನೆಲಮಂಗಲ ಕೆರೆಗಳ ಪುನಶ್ಚೇತನ ಕಾರ್ಯ',
    seoDescription: 'ಗ್ರಾಮೀಣ ಭಾಗದ ಕೆರೆಗಳ ಅಭಿವೃದ್ಧಿ ಕಾಮಗಾರಿ ಆರಂಭ.',
    seoKeywords: ['Lake', 'Nelamangala', 'Environment', 'Water'],
    canonicalUrl: null,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 10),
    updatedAt: new Date(),
    category: fallbackCategories[0],
    author: { id: 'usr-editor', email: 'editor@garjanenews.com', passwordHash: '', name: 'ಪರಿಸರ ವರದಿಗಾರ', avatar: null, role: 'EDITOR', bio: null, bioKn: null, location: null, phone: null, isActive: true, lastLoginAt: null, createdAt: new Date(), updatedAt: new Date() },
    reporter: null,
    location: fallbackLocations[0],
    tags: [],
    media: [],
    galleries: [],
    liveUpdates: [],
    views: [],
    relatedArticles: [],
    relatedTo: [],
    breakingNews: [],
    comments: [],
  },
];

export const fallbackBreakingNews = [
  {
    id: 'bn-1',
    headline: 'Nelamangala Highway 6-Lane Corridor Approved: Work to Commence Shortly',
    headlineKn: 'ನೆಲಮಂಗಲ-ತುಮಕೂರು ಹೆದ್ದಾರಿ 6 ಪಥದ ಮೇಲ್ಸೇತುವೆ ಕಾಮಗಾರಿಗೆ ಕೇಂದ್ರದ ಅನುಮೋದನೆ',
    level: 'BREAKING',
    articleId: 'art-1',
    article: { slug: 'nelamangala-highway-flyover-expansion-approved' },
  },
  {
    id: 'bn-2',
    headline: 'State Government Announces ₹2,000 Crore Relief Package for Rural Farmers',
    headlineKn: 'ರಾಜ್ಯ ಸರ್ಕಾರದ ಮಹತ್ವದ ತೀರ್ಮಾನ: ರೈತರ ನೆರವಿಗೆ ₹2,000 ಕೋಟಿ ಪರಿಹಾರ ಘೋಷಣೆ',
    level: 'URGENT',
    articleId: 'art-2',
    article: { slug: 'karnataka-cabinet-key-decisions-farmers-loan-relief' },
  },
];

export const fallbackVideos: VideoWithRelations[] = [
  {
    id: 'vid-1',
    title: 'Nelamangala Highway Traffic Ground Report: What Commuters Face Daily',
    titleKn: 'ನೆಲಮಂಗಲ ಟೋಲ್ ಬಳಿ ನಿತ್ಯದ ನರಕಯಾತನೆ: ಗರ್ಜನೆ ನ್ಯೂಸ್ ಗ್ರೌಂಡ್ ರಿಪೋರ್ಟ್',
    description: 'Special investigative report on the bottleneck near Nelamangala toll gate and how the new corridor will solve it.',
    descriptionKn: 'ನೆಲಮಂಗಲ ಟೋಲ್ ಗೇಟ್ ಬಳಿ ಸಂಚಾರ ದಟ್ಟಣೆ ಕುರಿತು ಗರ್ಜನೆ ನ್ಯೂಸ್ ವಿಶೇಷ ನೇರ ವರದಿ.',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    thumbnailUrl: 'https://images.unsplash.com/photo-1545459720-aac8509eb02c?w=800&auto=format&fit=crop&q=80',
    duration: 380,
    categoryId: 'cat-nelamangala',
    locationId: 'loc-nelamangala',
    reporterId: 'rep-nelamangala',
    viewCount: 18450,
    isPublished: true,
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 12),
    tags: ['Nelamangala', 'GroundReport', 'Traffic'],
    createdAt: new Date(),
    updatedAt: new Date(),
    category: fallbackCategories[0],
    location: fallbackLocations[0],
    reporter: null,
  },
  {
    id: 'vid-2',
    title: 'APMC Market Trends: Live Report on Vegetable Prices from Rural Bengaluru',
    titleKn: 'ತರಕಾರಿ ಬೆಲೆ ಏರಿಳಿತ: ಯಶವಂತಪುರ ಹಾಗೂ ನೆಲಮಂಗಲ ಎಪಿಎಂಸಿ ನೇರ ವರದಿ',
    description: 'Farmers and wholesalers discuss produce prices, supply chain logistics, and monsoon projections.',
    descriptionKn: 'ರೈತರು ಮತ್ತು ವ್ಯಾಪಾರಿಗಳೊಂದಿಗೆ ನೇರ ಮಾತುಕತೆ: ಮಾರುಕಟ್ಟೆ ಸ್ಥಿತಿಗತಿ ಪರಿಶೀಲನೆ.',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    thumbnailUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800&auto=format&fit=crop&q=80',
    duration: 260,
    categoryId: 'cat-business',
    locationId: 'loc-bengaluru-rural',
    reporterId: null,
    viewCount: 12300,
    isPublished: true,
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 24),
    tags: ['APMC', 'Farming', 'Karnataka'],
    createdAt: new Date(),
    updatedAt: new Date(),
    category: fallbackCategories[7],
    location: fallbackLocations[1],
    reporter: null,
  },
];

export const fallbackAds = [
  {
    id: 'ad-top-1',
    name: 'Garjane Local Business Sponsor',
    type: 'banner',
    imageUrl: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=728&h=90&auto=format&fit=crop&q=80',
    videoUrl: null,
    targetUrl: 'https://garjanenews.com/advertise',
    htmlCode: null,
    position: 'top-banner',
    width: 728,
    height: 90,
    startDate: null,
    endDate: null,
    isActive: true,
    priority: 1,
    impressions: 120,
    clicks: 14,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'ad-sidebar-1',
    name: 'Garjane Digital Subscription',
    type: 'sidebar',
    imageUrl: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?w=300&h=400&auto=format&fit=crop&q=80',
    videoUrl: null,
    targetUrl: 'https://garjanenews.com/newsletter',
    htmlCode: null,
    position: 'sidebar',
    width: 300,
    height: 400,
    startDate: null,
    endDate: null,
    isActive: true,
    priority: 1,
    impressions: 95,
    clicks: 8,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'ad-infeed-1',
    name: 'Garjane News Mobile App',
    type: 'in-feed',
    imageUrl: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800&h=200&auto=format&fit=crop&q=80',
    videoUrl: null,
    targetUrl: 'https://garjanenews.com',
    htmlCode: null,
    position: 'in-feed',
    width: 800,
    height: 200,
    startDate: null,
    endDate: null,
    isActive: true,
    priority: 1,
    impressions: 70,
    clicks: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const fallbackGalleries: (PhotoGallery & { images: GalleryImage[] })[] = [
  {
    id: 'gallery-1',
    articleId: 'art-1',
    title: 'Nelamangala Highway Infrastructure & Local Development',
    titleKn: 'ನೆಲಮಂಗಲ ಹೆದ್ದಾರಿ ಕಾಮಗಾರಿ ಮತ್ತು ಸ್ಥಳೀಯ ಅಭಿವೃದ್ಧಿ ಚಿತ್ರಾವಳಿ',
    description: 'Exclusive photos capturing the highway expansion and flyover progress in Nelamangala taluk.',
    descriptionKn: 'ನೆಲಮಂಗಲ ಫ್ಲೈಓವರ್ ಮತ್ತು ಹೆದ್ದಾರಿ ಕಾಮಗಾರಿಯ ಪ್ರಮುಖ ಚಿತ್ರಗಳು ಹಾಗೂ ಸ್ಥಳೀಯ ಅಭಿವೃದ್ಧಿ ದೃಶ್ಯಗಳು.',
    coverImage: 'https://images.unsplash.com/photo-1545459720-aac8509eb02c?w=1200&auto=format&fit=crop&q=80',
    imageCount: 4,
    displayOrder: 1,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24),
    updatedAt: new Date(),
    images: [
      {
        id: 'img-1-1',
        galleryId: 'gallery-1',
        url: 'https://images.unsplash.com/photo-1545459720-aac8509eb02c?w=1200&auto=format&fit=crop&q=80',
        alt: 'Nelamangala Highway Elevated Corridor',
        caption: 'Elevated highway corridor connecting Bengaluru and Tumakuru via Nelamangala.',
        captionKn: 'ಬೆಂಗಳೂರು-ತುಮಕೂರು ಸಂಪರ್ಕಿಸುವ ನೆಲಮಂಗಲ ಎಲಿವೇಟೆಡ್ ಹೆದ್ದಾರಿ ಕಾರಿಡಾರ್.',
        width: 1200,
        height: 800,
        displayOrder: 0,
        createdAt: new Date(),
      },
      {
        id: 'img-1-2',
        galleryId: 'gallery-1',
        url: 'https://images.unsplash.com/photo-1590486803833-1c5dc8ddd4c8?w=1200&auto=format&fit=crop&q=80',
        alt: 'Underpass and Flyover Pier Construction',
        caption: 'Pillars and ramp engineering works along the Nelamangala junction.',
        captionKn: 'ನೆಲಮಂಗಲ ಜಂಕ್ಷನ್ ಬಳಿ ಫ್ಲೈಓವರ್ ಪಿಲ್ಲರ್ ಮತ್ತು ರ್‍ಯಾಂಪ್ ಕಾಮಗಾರಿ.',
        width: 1200,
        height: 800,
        displayOrder: 1,
        createdAt: new Date(),
      },
      {
        id: 'img-1-3',
        galleryId: 'gallery-1',
        url: 'https://images.unsplash.com/photo-1584463699039-50ebac8e3c15?w=1200&auto=format&fit=crop&q=80',
        alt: 'Toll Plaza Traffic Flow',
        caption: 'Seamless multi-lane traffic flow near the Nelamangala toll gate.',
        captionKn: 'ನೆಲಮಂಗಲ ಟೋಲ್ ಗೇಟ್ ಬಳಿ ಸುಗಮ ಸಂಚಾರ ವ್ಯವಸ್ಥೆ.',
        width: 1200,
        height: 800,
        displayOrder: 2,
        createdAt: new Date(),
      },
      {
        id: 'img-1-4',
        galleryId: 'gallery-1',
        url: 'https://images.unsplash.com/photo-1506521781263-d8422e82f27a?w=1200&auto=format&fit=crop&q=80',
        alt: 'Aerial View of Nelamangala Town',
        caption: 'Aerial panorama of rapid urban and logistics growth around Nelamangala.',
        captionKn: 'ನೆಲಮಂಗಲ ಪಟ್ಟಣ ಮತ್ತು ಲಾಜಿಸ್ಟಿಕ್ಸ್ ಹಬ್‌ನ ವಿಹಂಗಮ ನೋಟ.',
        width: 1200,
        height: 800,
        displayOrder: 3,
        createdAt: new Date(),
      },
    ],
  },
  {
    id: 'gallery-2',
    articleId: 'art-2',
    title: 'Karnataka Rural Heritage & Agricultural Landscape',
    titleKn: 'ಕರ್ನಾಟಕದ ಗ್ರಾಮೀಣ ಜನಜೀವನ ಮತ್ತು ಕೃಷಿ ಸಂಸ್ಕೃತಿ',
    description: 'A visual journey through Karnataka rural heartlands, harvest festivals, and farming communities.',
    descriptionKn: 'ಬೆಂಗಳೂರು ಗ್ರಾಮಾಂತರ ಹಾಗೂ ಕರ್ನಾಟಕದ ರೈತಾಪಿ ಬದುಕು, ಕೃಷಿ ಪದ್ಧತಿ ಮತ್ತು ಹಬ್ಬಗಳ ಅಪರೂಪದ ಚಿತ್ರಗಳು.',
    coverImage: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=1200&auto=format&fit=crop&q=80',
    imageCount: 4,
    displayOrder: 2,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48),
    updatedAt: new Date(),
    images: [
      {
        id: 'img-2-1',
        galleryId: 'gallery-2',
        url: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=1200&auto=format&fit=crop&q=80',
        alt: 'Lush Green Fields in Karnataka',
        caption: 'Bountiful paddy and ragi fields in rural Bengaluru during monsoon.',
        captionKn: 'ಮುಂಗಾರು ಹಂಗಾಮಿನಲ್ಲಿ ಹಚ್ಚಹಸಿರಿನ ರಾಗಿ ಮತ್ತು ಭತ್ತದ ಗದ್ದೆಗಳು.',
        width: 1200,
        height: 800,
        displayOrder: 0,
        createdAt: new Date(),
      },
      {
        id: 'img-2-2',
        galleryId: 'gallery-2',
        url: 'https://images.unsplash.com/photo-1595974482597-4b8da8879bc5?w=1200&auto=format&fit=crop&q=80',
        alt: 'Local Farmers Market APMC',
        caption: 'Early morning vegetable trade and commerce at the Nelamangala APMC yard.',
        captionKn: 'ನೆಲಮಂಗಲ ಎಪಿಎಂಸಿ ಮಾರುಕಟ್ಟೆಯಲ್ಲಿ ಬೆಳಗಿನ ತರಕಾರಿ ವ್ಯಾಪಾರ.',
        width: 1200,
        height: 800,
        displayOrder: 1,
        createdAt: new Date(),
      },
      {
        id: 'img-2-3',
        galleryId: 'gallery-2',
        url: 'https://images.unsplash.com/photo-1574943320219-553eb213f72d?w=1200&auto=format&fit=crop&q=80',
        alt: 'Traditional Cattle and Dairy Farming',
        caption: 'Dairy farming continues to be the backbone of rural livelihoods in the region.',
        captionKn: 'ಗ್ರಾಮೀಣ ಆರ್ಥಿಕತೆಯ ಬೆನ್ನೆಲುಬಾಗಿರುವ ಹೈನುಗಾರಿಕೆ ಮತ್ತು ಜಾನುವಾರು ಪೋಷಣೆ.',
        width: 1200,
        height: 800,
        displayOrder: 2,
        createdAt: new Date(),
      },
      {
        id: 'img-2-4',
        galleryId: 'gallery-2',
        url: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=1200&auto=format&fit=crop&q=80',
        alt: 'Sunset over Lake and Coconut Groves',
        caption: 'Serene sunset across water tanks and coconut orchards in southern Karnataka.',
        captionKn: 'ಗ್ರಾಮಾಂತರ ಪ್ರದೇಶದ ಕೆರೆ ಮತ್ತು ತೆಂಗಿನ ತೋಟಗಳ ನಡುವೆ ಮುಸ್ಸಂಜೆಯ ಸೌಂದರ್ಯ.',
        width: 1200,
        height: 800,
        displayOrder: 3,
        createdAt: new Date(),
      },
    ],
  },
];
